Added table storage deletion to the Storage layer and removed the del…
linkedin/openhouse pull request #143
Opened 2024-07-26 19:06 UTC by vikrambohra

…etion logic from the catalog layer

## Summary
Added table location deletion logic in the Storage API layer. 
1. Created a Table deallocation method in the Storage interface for deleting table location along with implementations for various storages (LocalStorage, HdfsStorage, S3Storage)
2. Integrated the above logic into the catalog and repo layer. 

[Issue](https://github.com/linkedin/openhouse/issues/#nnn)] Briefly discuss the summary of the changes made in this 
pull request in 2-3 lines.

## Changes

- [ ] Client-facing API Changes
- [ ] Internal API Changes
- [ ] Bug Fixes
- [x] New Features
- [ ] Performance Improvements
- [ ] Code Style
- [x] Refactoring
- [ ] Documentation
- [ ] Tests

For all the boxes checked, please include additional details of the changes made in this pull request.  

## Testing Done

- [ ] Manually Tested on local docker setup. Please include commands ran, and their output.
- [ ] Added new tests for the changes made.
- [x] Updated existing tests to reflect the changes made.
- [ ] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in production. Please explain.

Updated LocalStorgeTest and BaseStorageTest with testing for deallocateTableLocation
# Additional Information
- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the description.

For all the boxes checked, include additional details of the changes made in this pull request.

2024-07-26 19:38 UTC, HotSushi commented on cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/BaseStorage.java
> +    List<IOException> exceptions = new ArrayList<>();
let's leave this as a no-op for `BaseStorage` and add some log for example: "deallocateTableLocation action not defined, skipping deallocation for Storage: XYZ"

Files.walk code will likely not work for storages outside of local system like gcs, or s3 or abs.

2024-07-26 19:46 UTC, HotSushi reviewed
PR is looking great, have a comment on BaseStorages implementation and s3 implementation. Also requesting a docker test for s3 minio setup.

2024-07-26 19:46 UTC, HotSushi commented on cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/local/LocalStorage.java
> +  public void deallocateTableLocation(String location, String tableCreator) throws IOException {
💯

2024-07-26 19:46 UTC, HotSushi commented on cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/s3/S3Storage.java
> +          .deleteBucket(DeleteBucketRequest.builder().bucket(location).build());
currently bucket is defined at cluster level, this code will likely not work for bucket/db/tbl and it'll end up deleting all data.
can we check how S3FileIO implements  SupportsPrefixOperations? and use that code as reference

2024-07-26 19:46 UTC, HotSushi commented on cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/s3/S3Storage.java
> +          .deleteBucket(DeleteBucketRequest.builder().bucket(location).build());
Lets also perform a docker compose test for this in s3

2024-07-26 19:50 UTC, maluchari commented on services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
> +              "Exception while deleting table location %s for %s.%s",
Consider logging the table location. We can skip location details in errors thrown back to clients to maintain table abstraction.

2024-07-26 19:54 UTC, maluchari commented on cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/Storage.java
> +   * @param tableCreator the creator of the table
This need not tableCreator necessarily for all underlying storages.  May be actingPrincipal?

2024-07-26 20:05 UTC, maluchari commented on services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
> +        false);
Why do we still need this boolean? I think functionality wise this change will already impact any overridden implementations of the OpenHouseInternalCatalog until changes are made in the overridden implementations.  And also the boolean is used to determine whether this should be a soft or hard delete. Considering this logic is moved here should we still need the boolean flag?

2024-07-29 13:29 UTC, sumedhsakdeo requested changes

2024-07-29 13:29 UTC, sumedhsakdeo commented on cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/BaseStorage.java
> +  public void deallocateTableLocation(String location, String tableCreator) throws IOException {
What is the main objective of this method? I understand what is does but why do we need it is not clear?
Can you update the PR description and javadoc?

2024-08-05 17:38 UTC, vikrambohra commented
Adding deallocateTableLocation in the storage interface does not make sense atm. The implementation in S3Storage is complicated and requires significant code duplication from S3FileIO.  Currently implemented internally in li-openhouse. Will revisit this if required

2024-08-05 17:38 UTC, closed without merging