Setup Java 17 when building repo in github CI workflow
linkedin/openhouse pull request #209
Opened 2024-09-24 13:46 UTC by teamurko

## Summary
Update setup java action to build with Java17, update docs. The change should be non-consequential since the source and target byte code are still Java 1.8 compatible.

## Changes

- [ ] Client-facing API Changes
- [ ] Internal API Changes
- [ ] Bug Fixes
- [ ] New Features
- [ ] Performance Improvements
- [ ] Code Style
- [ ] Refactoring
- [x] Documentation
- [ ] Tests
- [x] Upgrade

For all the boxes checked, please include additional details of the changes made in this pull request.  

## Testing Done

- [ ] Manually Tested on local docker setup. Please include commands ran, and their output.
- [ ] Added new tests for the changes made.
- [ ] Updated existing tests to reflect the changes made.
- [x] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in production. Please explain.

For all the boxes checked, include a detailed description of the testing done for the changes made in this pull request.

# Additional Information

- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the description.

For all the boxes checked, include additional details of the changes made in this pull request.

2024-09-24 16:45 UTC, rohitkum2506 approved these changes

2024-09-24 16:49 UTC, autumnust requested changes
shall we have both version in CI for the time being?

2024-09-24 17:07 UTC, abhisheknath2011 commented on .github/workflows/build-tag-publish.yml
> +          java-version: '17'
Is it possible to support both the version while upgrade is in progress?

2024-09-24 17:19 UTC, teamurko commented
> shall we have both version in CI for the time being?

It's byte code 8, no need to publish two artifacts, when we build for 2 targets we can publish both

2024-09-24 18:43 UTC, maluchari approved these changes

2024-09-25 16:29 UTC, autumnust approved these changes

2024-09-25 16:41 UTC, abhisheknath2011 commented on .github/workflows/build-tag-publish.yml
> +          java-version: '17'
So this should not impact internal OH upgrade based on comments in this PR.

2024-09-25 16:42 UTC, abhisheknath2011 approved these changes

2024-09-25 16:44 UTC, merged