Support Table History Policy in Snapshot Expiration Job
linkedin/openhouse pull request #274
Opened 2024-12-24 00:24 UTC by Will-Lo

## Summary

[[Issue](https://github.com/linkedin/openhouse/issues/#nnn)] Briefly discuss the summary of the changes made in this 
pull request in 2-3 lines.

Following up from https://github.com/linkedin/openhouse/pull/262 and https://github.com/linkedin/openhouse/pull/259
this PR adds support for snapshot expiration table maintenance job to use the history policies defined.

Most notably snapshot expiration will follow the settings of `maxAge`, `granularity`, and `versions` as follows:
1. If maxAge is provided, it will expire snapshots older than maxAge in granularity timeunit. 
2. If versions is provided, it will retain the last versions snapshots regardless of their age.
3. If both are provided, it will prioritize maxAge; only retain up to versions number of snapshots younger than the maxAge. This is done by pruning the snapshots older than maxAge, and then running a second expiration to keeping N versions after that. 

Note: If versions are defined and there are less than N versions in the history, then there were not enough commits (within that timespan if defined). Snapshot expiration will always keep at least 1 version.

The default behavior of snapshot expiration job will remain the same, keep snapshots within the last 3 days.

## Changes

- [ ] Client-facing API Changes
- [ ] Internal API Changes
- [ ] Bug Fixes
- [ ] New Features
- [ ] Performance Improvements
- [ ] Code Style
- [ ] Refactoring
- [ ] Documentation
- [ ] Tests

For all the boxes checked, please include additional details of the changes made in this pull request.  

## Testing Done

- [ ] Manually Tested on local docker setup. Please include commands ran, and their output.
- [ ] Added new tests for the changes made.
- [ ] Updated existing tests to reflect the changes made.
- [ ] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in production. Please explain.

For all the boxes checked, include a detailed description of the testing done for the changes made in this pull request.

# Additional Information

- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the description.

For all the boxes checked, include additional details of the changes made in this pull request.

2025-01-02 21:26 UTC, autumnust requested changes

2025-01-02 21:26 UTC, autumnust commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
> +          .expireOlderThan(System.currentTimeMillis())
this is a bit unintuitive? For my knowledge: What will happen if older-than-now is not explicitly specified?

2025-01-02 21:26 UTC, autumnust commented on apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
> +          table, snapshotIds.subList(snapshotIds.size() - versionsToKeep, snapshotIds.size()));
how does it test the semantics of favoring maxAge when both spec coexists? I assume we need to create N + M  snapshots in total, with N > versionToKeep and all snapshots among N are oldThanMaxAge, and after calling expiration job we will have all N expired.

2025-01-02 21:49 UTC, Will-Lo commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
> +          .expireOlderThan(System.currentTimeMillis())
If it's not explicitly specified, then no snapshots would be deleted by this SQL statement. From the javadoc:
```
[ExpireSnapshots](https://javadoc.io/static/org.apache.iceberg/iceberg-api/1.7.1/org/apache/iceberg/ExpireSnapshots.html) retainLast​(int numSnapshots)
Retains the most recent ancestors of the current snapshot.
If a snapshot would be expired because it is older than the expiration timestamp, but is one of the numSnapshots most recent ancestors of the current state, it will be retained. This will not cause snapshots explicitly identified by id from expiring.

This may keep more than numSnapshots ancestors if snapshots are added concurrently. This may keep less than numSnapshots ancestors if the current table state does not have that many.

Parameters:
numSnapshots - the number of snapshots to retain
Returns:
this for method chaining
```
https://javadoc.io/doc/org.apache.iceberg/iceberg-api/latest/org/apache/iceberg/ExpireSnapshots.html#retainLast(int)

I agree it's not intuitive but it seems that's how the java API is set up, in the official iceberg documents the alternative is to set write properties to forcefully maintain a certain number of versions of the table, but I think we wanted to not affect writers. e.g. `write.metadata.previous-versions-max`

2025-01-02 23:10 UTC, Will-Lo commented on apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
> +          table, snapshotIds.subList(snapshotIds.size() - versionsToKeep, snapshotIds.size()));
Thanks, I added some tests around this and found a bug where `retainLast` would throw an exception if the `versionToKeep > N`

2025-01-04 01:58 UTC, jiang95-dev requested changes
One small change request.

2025-01-04 01:58 UTC, jiang95-dev commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/SnapshotsExpirationSparkApp.java
> +    public static final String VERSIONS = "0";
We can simply make `MAX_AGE` and `VERSIONS` int type to avoid type conversion.

2025-01-04 01:58 UTC, jiang95-dev commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
> +          .expireOlderThan(System.currentTimeMillis())
After looking into the iceberg code I found it not unintuitive.

Iceberg follows an **OR** strategy: Snapshots can either satisfy the maxAge or the versions restrictions. So when `expireOlderThan` is not explicitly defined, the maxAge is Infinite, and so all snapshots will be kept. When there are more snapshots in the versions than maxAge, those snapshots will also be kept.

On the contrary, Openhouse follows an **AND** strategy: Snapshots must satisfy both the maxAge and the versions restrictions. So it needs to call the iceberg API twice.

2025-01-06 19:44 UTC, autumnust approved these changes
thanks for adding the test cases for both configuration provided

2025-01-06 21:11 UTC, abhisheknath2011 commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/SnapshotsExpirationSparkApp.java
> +    if (maxAge == 0 && versions == 0) {
What happens if maxAge and versions both are 0? Should we apply default policy in such case like expire 3 days worth of snapshot?

2025-01-06 21:14 UTC, abhisheknath2011 commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/SnapshotsExpirationSparkApp.java
> +    if (maxAge == 0 && versions == 0) {
I see that default configuration is set to 3 days. Sounds good.

2025-01-06 21:17 UTC, abhisheknath2011 approved these changes
Thanks @Will-Lo

2025-01-06 22:16 UTC, jiang95-dev approved these changes
LGTM

2025-01-06 22:36 UTC, merged