Add Getting Started Guide
linkedin/openhouse pull request #55
Opened 2024-03-22 22:17 UTC by HotSushi

## Summary
This PR adds a getting started guide to the docsite. Its a quickstart tutorial to get something up and running quickly.

Language follows the ["Tutorial Language"](https://diataxis.fr/tutorials/)

## Changes
- [X] Documentation

For all the boxes checked, please include additional details of the changes made in this pull request.  

## Testing Done

- [X] Some other form of testing like staging or soak time in production. Please explain.
`npm run start` and captured snapshot image here:
![Uploading image.png…]()

2024-03-25 04:31 UTC, sumedhsakdeo requested changes
This is good, we should approach this user guide with a minimal set of commands 

1. build openhouse
2. run openhouse+spark+hdfs in docker
3. test create table, insert into, select from, enable sharing, and grant select

To avoid duplication in the documentation here and what we have in the [SETUP](https://github.com/linkedin/openhouse/blob/main/SETUP.md) guide. We could provide link the users to the SETUP guide.

Wdyt?

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +By the end of this walkthrough, we will have made some tables on OpenHouse, put data in them, retrieved the data
```suggestion
By the end of this walkthrough, we will have created some tables on OpenHouse, inserted data in them, and queried data.
```

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +and checked HDFS namenodes to see the data written.
```suggestion
```

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +Then, go to the location `infra/recipes/docker-compose/oh-hadoop-spark` and execute `docker compose up` command.
```suggestion
Execute `docker compose -f infra/recipes/docker-compose/oh-hadoop-spark/docker-compose.yml up -d --build` command to bring up docker container for openhouse services, spark and HDFS.
```

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +```
```suggestion
```

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +Voila! Just like that, we have all the core OpenHouse services up alongside Spark and Hadoop.
```suggestion
```

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +Let us  execute some basic SQL commands to create table, add data and retrieve the data.
```suggestion
Let us execute some basic SQL commands to create table, add data and query data.
```

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +running the [REST-based catalog service](./intro.md#catalog-service).
```suggestion
running the [OpenHouse Catalog Service](./intro.md#catalog-service).
```

2024-03-25 04:31 UTC, sumedhsakdeo commented on docs/getting_started.md
> +in the previous section.
```suggestion
```
TMI

2024-03-26 20:04 UTC, HotSushi commented
> This is good, we should approach this user guide with a minimal set of commands
> 
> 1. build openhouse
> 2. run openhouse+spark+hdfs in docker
> 3. test create table, insert into, select from, enable sharing, and grant select
> 
> To avoid duplication in the documentation here and what we have in the [SETUP](https://github.com/linkedin/openhouse/blob/main/SETUP.md) guide. We could provide link the users to the SETUP guide.
> 
> Wdyt?

Added a link to the source of truth ie: SETUP guide. 

Agree on keeping it minimal and practical!

2024-03-27 01:01 UTC, sumedhsakdeo approved these changes
Nice!

2024-03-27 01:44 UTC, merged