Minor fixes
linkedin/openhouse pull request #64
Opened 2024-04-04 04:38 UTC by y242yang

## Summary

I need to make multiple changes here 
(1) Make sfd job type arguments configurable
(2) Make a few member variables and methods protected to subclasses have access or can override them.

## Changes

- [ ] Client-facing API Changes
- [ ] Internal API Changes
- [ ] Bug Fixes
- [ ] New Features
- [ ] Performance Improvements
- [x] Code Style
- [ ] Refactoring
- [ ] Documentation
- [ ] Tests

For all the boxes checked, please include additional details of the changes made in this pull request.  

## Testing Done

- [ ] Manually Tested on local docker setup. Please include commands ran, and their output.
- [ ] Added new tests for the changes made.
- [x] Updated existing tests to reflect the changes made.
- [x] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in production. Please explain.

Code style changes

For all the boxes checked, include a detailed description of the testing done for the changes made in this pull request.

# Additional Information

- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the description.

For all the boxes checked, include additional details of the changes made in this pull request.

2024-04-04 05:17 UTC, sumedhsakdeo requested changes
Please update PR title and update description to describe what was the bug that this PR is fixing.

2024-04-04 17:02 UTC, teamurko commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/StagedFilesDeletionSparkApp.java
> +            Integer.parseInt(cmdLine.getOptionValue("daysOld", "10")),
default doesn't have to change

2024-04-05 02:48 UTC, y242yang commented on apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/StagedFilesDeletionSparkApp.java
> +            Integer.parseInt(cmdLine.getOptionValue("daysOld", "10")),
changed back to 3

2024-04-05 02:58 UTC, sumedhsakdeo approved these changes

2024-04-05 03:37 UTC, merged